#!/usr/bin/env python3
"""Build js/data/basemap.js: a self-hosted, lat/lng GeoJSON basemap of the four
countries so the offline map needs NO external tiles (the old Protomaps demo bucket
is dead). MapLibre renders these polygons directly; GPS, pins, places and routes draw
on top. Streets are not included — this is a reliable always-offline geometry base.

Re-run after changing the country set:  python3 scripts/build_basemap.py
Reads the cached /tmp/mk_<cca3>.geo.json files (mledoze/countries, public domain).
"""
import json, math, os

COUNTRIES = [('th', 'tha', 'Thailand'), ('vi', 'vnm', 'Vietnam'), ('kh', 'khm', 'Cambodia'), ('la', 'lao', 'Laos')]
EPS = 0.02       # simplify tolerance in degrees (~2 km) — plenty for a basemap
AREA_MIN = 0.01  # deg^2 — drop tiny specks, keep mainland + big islands


def load(cca3):
    return json.load(open(f'/tmp/mk_{cca3}.geo.json'))


def polys_of(geo):
    feats = geo['features'] if geo.get('type') == 'FeatureCollection' else [geo]
    g = feats[0]['geometry']
    return [g['coordinates']] if g['type'] == 'Polygon' else g['coordinates']


def ring_area(ring):
    a = 0.0
    for i in range(len(ring) - 1):
        x1, y1 = ring[i]; x2, y2 = ring[i + 1]
        a += x1 * y2 - x2 * y1
    return abs(a) / 2.0


def perp(p, a, b):
    (x, y), (x1, y1), (x2, y2) = p, a, b
    dx, dy = x2 - x1, y2 - y1
    if dx == 0 and dy == 0:
        return math.hypot(x - x1, y - y1)
    t = ((x - x1) * dx + (y - y1) * dy) / (dx * dx + dy * dy)
    t = max(0, min(1, t))
    return math.hypot(x - (x1 + t * dx), y - (y1 + t * dy))


def rdp(points, eps):
    if len(points) < 3:
        return points
    dmax, idx = 0.0, 0
    a, b = points[0], points[-1]
    for i in range(1, len(points) - 1):
        d = perp(points[i], a, b)
        if d > dmax:
            dmax, idx = d, i
    if dmax > eps:
        return rdp(points[:idx + 1], eps)[:-1] + rdp(points[idx:], eps)
    return [a, b]


def rnd(ring):
    return [[round(x, 4), round(y, 4)] for x, y in ring]


features = []
for code, cca3, name in COUNTRIES:
    multi = []
    for poly in polys_of(load(cca3)):
        if ring_area(poly[0]) < AREA_MIN:
            continue
        rings = []
        for ring in poly:
            simp = rdp(ring, EPS)
            if len(simp) >= 4:
                rings.append(rnd(simp))
        if rings:
            multi.append(rings)
    features.append({
        'type': 'Feature',
        'properties': {'id': code, 'name': name},
        'geometry': {'type': 'MultiPolygon', 'coordinates': multi},
    })

fc = {'type': 'FeatureCollection', 'features': features}
out = (
    "// AUTO-GENERATED by scripts/build_basemap.py — do not edit by hand.\n"
    "// Self-hosted GeoJSON basemap of the four countries (mledoze/countries, public\n"
    "// domain), simplified at build time so the offline map needs no external tiles.\n"
    "export const BASEMAP = " + json.dumps(fc, ensure_ascii=False) + ";\n"
)
dest = os.path.join(os.path.dirname(__file__), '..', 'js', 'data', 'basemap.js')
open(dest, 'w', encoding='utf-8').write(out)
pts = sum(len(r) for f in features for poly in f['geometry']['coordinates'] for r in poly)
print(f"wrote {dest}  {len(out)} bytes  ~{pts} points")
