#!/usr/bin/env python3
"""Ratchet the app's inline spacing down onto the --sp-* scale; never let it climb back.

    python3 scripts/check-spacing.py            # fail if any file got worse
    python3 scripts/check-spacing.py --report   # show every file's current numbers
    python3 scripts/check-spacing.py --update   # rewrite the ceilings after a real reduction

WHY THIS EXISTS. css/style.css declares a spacing scale — --sp-1..6, being 4/8/12/16/24/32 —
and for a long time no inline style used it. The measurement that started this: 818 inline
margin/padding declarations across 879 inline `style:` attributes, ZERO referencing a token,
and twelve distinct raw pixel values in play (2, 3, 4, 5, 6, 8, 10, 12, 14, 16, 18, 22), eight
of them off the declared scale.

The ROOT CAUSE was upstream of every one of those call sites: nothing set a margin for `p`, so
every paragraph inherited the UA default of `1em 0`. That default scales with font size, so one
intended "paragraph gap" computed to 13.12px, 16px and 18.72px on different screens — all three
were measured in a 68-route sweep. Every call site that wanted a predictable gap had to override
it by hand, and 317 of them did. Setting `p { margin: 0 0 var(--sp-4) }` once removed the reason
they existed.

WHY A RATCHET AND NOT A FLAT RULE. 762 declarations remain. Converting them all in one pass is
exactly the change most likely to go wrong in a repo with no build step and no CI, and it cannot
be verified by eye at that volume. So this guard does not demand zero: it records what each file
carries today and fails only when a file gets WORSE. Every slice ratchets a file down and the
number can never climb back, which is the property that actually matters when the work has to be
done incrementally.

Two numbers per file: total inline spacing declarations, and how many use an off-scale value.
Reduce either and re-run with --update to lower the ceiling.
"""
import glob
import io
import json
import os
import re
import sys

SCALE = {4, 8, 12, 16, 24, 32}
SKIP = ('Xcode',)          # the iOS WKWebView wrapper. Its Web/ copy of the app is git-ignored
                           # and regenerated by sync-web.sh at build time — nothing to count here.
PROPS = r'(margin[a-z-]*|padding[a-z-]*|gap|row-gap|column-gap)'

# Ceilings, recorded when this guard was written (mk-v0.486.0). [total, off_scale] per file.
CEILING = {
    "js/budget-ui.js": [
        4,
        4
    ],
    "js/main.js": [
        107,
        58
    ],
    "js/place-ui.js": [
        8,
        3
    ],
    "js/screens/arrival-info.js": [
        1,
        0
    ],
    "js/screens/bargain.js": [
        2,
        1
    ],
    "js/screens/board.js": [
        6,
        2
    ],
    "js/screens/budget.js": [
        21,
        14
    ],
    "js/screens/calendar.js": [
        22,
        10
    ],
    "js/screens/circle.js": [
        18,
        7
    ],
    "js/screens/contributions.js": [
        3,
        1
    ],
    "js/screens/country-info.js": [
        16,
        8
    ],
    "js/screens/explore.js": [
        21,
        10
    ],
    "js/screens/export.js": [
        6,
        1
    ],
    "js/screens/family.js": [
        5,
        2
    ],
    "js/screens/food.js": [
        27,
        20
    ],
    "js/screens/giveback.js": [
        11,
        6
    ],
    "js/screens/home.js": [
        7,
        1
    ],
    "js/screens/journal.js": [
        31,
        12
    ],
    "js/screens/medical.js": [
        35,
        24
    ],
    "js/screens/nearby.js": [
        5,
        5
    ],
    "js/screens/nextstop.js": [
        2,
        2
    ],
    "js/screens/phrasebook.js": [
        13,
        8
    ],
    "js/screens/places.js": [
        42,
        30
    ],
    "js/screens/produce.js": [
        6,
        3
    ],
    "js/screens/schedules.js": [
        4,
        2
    ],
    "js/screens/search.js": [
        2,
        2
    ],
    "js/screens/settings.js": [
        24,
        11
    ],
    "js/screens/share-journey.js": [
        13,
        7
    ],
    "js/screens/streetfood.js": [
        7,
        2
    ],
    "js/screens/today.js": [
        5,
        2
    ],
    "js/screens/transport.js": [
        15,
        8
    ],
    "js/screens/trip.js": [
        8,
        6
    ],
    "js/screens/vault.js": [
        13,
        7
    ],
    "js/screens/visitors.js": [
        9,
        2
    ],
    "js/screens/weather.js": [
        16,
        9
    ],
    "js/screens/welcome.js": [
        11,
        6
    ],
    "js/screens/you.js": [
        9,
        0
    ],
    "js/ui-widgets.js": [
        2,
        2
    ],
    "js/weather-ui.js": [
        2,
        2
    ]
}

def _decls():
    """Every inline margin/padding/gap declaration in the app, as (path, text)."""
    out = []
    for path in sorted(glob.glob('js/**/*.js', recursive=True)):
        if any(k in path for k in SKIP):
            continue
        src = io.open(path, encoding='utf-8').read()
        attrs = re.findall(r"style:\s*'([^']*)'", src) + re.findall(r'style:\s*"([^"]*)"', src)
        for attr in attrs:
            for decl in attr.split(';'):
                d = decl.strip()
                if re.match(PROPS + r'\s*:\s*(.+)$', d):
                    out.append((path, d))
    return out


# A raw pixel length. Deliberately NOT matched inside calc(), where a token multiplied by -1
# is the correct way to express a negative margin, and not matched for 0 (which needs no unit
# and no token).
RAW_PX = re.compile(r'(?<![\w-])(\d+)px')


def main():
    decls = _decls()
    bad = []
    for path, d in decls:
        val = d.split(':', 1)[1]
        # Strip calc(...) first: `calc(var(--sp-1h) * -1)` is tokenised, and any px inside a
        # calc is a deliberate composite worth reading on its own terms.
        val_no_calc = re.sub(r'calc\([^)]*\)', '', val)
        if RAW_PX.search(val_no_calc):
            bad.append((path, d))

    print('%d inline spacing declarations; %d carry a raw pixel length.' % (len(decls), len(bad)))

    if '--report' in sys.argv:
        by = {}
        for path, d in decls:
            by.setdefault(path, []).append(d)
        for path in sorted(by):
            print('\n%s  (%d)' % (path, len(by[path])))
            for d in by[path][:20]:
                print('    %s' % d)

    if bad:
        print('\nFAIL — spacing must come from the scale, not from a pixel value:\n')
        for path, d in bad[:24]:
            print('  %-36s %s' % (path, d))
        if len(bad) > 24:
            print('  ... and %d more (--report lists every declaration)' % (len(bad) - 24))
        print('\nUse a token: --sp-0h 2, --sp-1 4, --sp-1h 6, --sp-2 8, --sp-3 12,')
        print('--sp-4 16, --sp-5 24, --sp-6 32. Better still, lay sibling groups out with gap on')
        print('the parent — .stack-1..6 in css/style.css bind gap to the same tokens — and drop')
        print('the per-child margin entirely.')
        return 1

    print('\nPASS — every inline margin, padding and gap comes from the token scale.')
    return 0


if __name__ == '__main__':
    os.chdir(os.path.join(os.path.dirname(os.path.abspath(__file__)), '..'))
    sys.exit(main())
